/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import java.awt.Color;
import java.awt.Toolkit;
import java.io.File;
import java.io.FileWriter;
import java.io.IOException;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.ImageIO;
import javax.swing.JOptionPane;

/**
 *
 * @author 7heXiMiK
 */
public class Authorization extends javax.swing.JFrame {

    private Connection conn = null;
    MainMenu m = null;
    private int reg = 0;

    @Override
    public void setName(String name) {
        super.setName(name); //To change body of generated methods, choose Tools | Templates.
    }

    /**
     * Creates new form Authorization
     */
    public Authorization() {
        initComponents();
        File IconForm = new File("Photo/labyrinth.png");
        try {

            this.setIconImage(ImageIO.read(IconForm));
        } catch (IOException ex) {
            Logger.getLogger(Authorization.class.getName()).log(Level.SEVERE, null, ex);
        }
        try {
            start();
        } catch (IOException ex) {
            Logger.getLogger(Authorization.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel6 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        lblLogin1 = new javax.swing.JLabel();
        jSeparator3 = new javax.swing.JSeparator();
        pnlBody = new javax.swing.JPanel();
        txtPass = new javax.swing.JTextField();
        btnLogin = new javax.swing.JButton();
        lblPass = new javax.swing.JLabel();
        lblLogin = new javax.swing.JLabel();
        txtLogin = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        pnlActiv = new javax.swing.JPanel();
        lblActiv = new javax.swing.JLabel();
        lblRegister = new javax.swing.JLabel();
        lblPib = new javax.swing.JLabel();
        txtPib = new javax.swing.JTextField();
        jSeparator4 = new javax.swing.JSeparator();
        btnUpdateCon = new javax.swing.JButton();
        btnBack = new javax.swing.JButton();
        lblTitle = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        btnSet = new javax.swing.JLabel();
        btnHide = new javax.swing.JButton();
        btnExit = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        jLabel6.setText("jLabel6");

        jButton3.setBackground(new java.awt.Color(126, 87, 195));
        jButton3.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jButton3.setText("Увійти");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        lblLogin1.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        lblLogin1.setForeground(new java.awt.Color(0, 0, 0));
        lblLogin1.setText("Логін");

        jSeparator3.setBackground(new java.awt.Color(255, 0, 255));
        jSeparator3.setForeground(new java.awt.Color(255, 0, 204));
        jSeparator3.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jSeparator3.setDebugGraphicsOptions(javax.swing.DebugGraphics.NONE_OPTION);
        jSeparator3.setFont(new java.awt.Font("Dialog", 0, 48)); // NOI18N

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(153, 51, 0));
        setLocationByPlatform(true);
        setUndecorated(true);
        setPreferredSize(new java.awt.Dimension(700, 583));
        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                formMouseEntered(evt);
            }
        });
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        pnlBody.setBackground(new java.awt.Color(0, 0, 102));
        pnlBody.setForeground(new java.awt.Color(102, 0, 102));
        pnlBody.setPreferredSize(new java.awt.Dimension(360, 535));
        pnlBody.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                pnlBodyMouseEntered(evt);
            }
        });

        txtPass.setBackground(new java.awt.Color(0, 0, 102));
        txtPass.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        txtPass.setForeground(new java.awt.Color(255, 255, 255));
        txtPass.setBorder(null);

        btnLogin.setBackground(new java.awt.Color(0, 51, 204));
        btnLogin.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        btnLogin.setText("Увійти");
        btnLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLoginActionPerformed(evt);
            }
        });

        lblPass.setBackground(new java.awt.Color(255, 255, 255));
        lblPass.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        lblPass.setForeground(new java.awt.Color(255, 255, 255));
        lblPass.setText("Пароль");

        lblLogin.setBackground(new java.awt.Color(255, 255, 255));
        lblLogin.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        lblLogin.setForeground(new java.awt.Color(255, 255, 255));
        lblLogin.setText("Логін");

        txtLogin.setBackground(new java.awt.Color(0, 0, 102));
        txtLogin.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        txtLogin.setForeground(new java.awt.Color(255, 255, 255));
        txtLogin.setBorder(null);
        txtLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtLoginActionPerformed(evt);
            }
        });

        jSeparator1.setBackground(new java.awt.Color(255, 255, 255));
        jSeparator1.setForeground(new java.awt.Color(255, 0, 204));
        jSeparator1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jSeparator1.setDebugGraphicsOptions(javax.swing.DebugGraphics.NONE_OPTION);
        jSeparator1.setFont(new java.awt.Font("Dialog", 0, 48)); // NOI18N

        jSeparator2.setBackground(new java.awt.Color(255, 255, 255));
        jSeparator2.setForeground(new java.awt.Color(255, 0, 204));
        jSeparator2.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jSeparator2.setDebugGraphicsOptions(javax.swing.DebugGraphics.NONE_OPTION);
        jSeparator2.setFont(new java.awt.Font("Dialog", 0, 48)); // NOI18N

        pnlActiv.setBackground(new java.awt.Color(255, 0, 0));

        javax.swing.GroupLayout pnlActivLayout = new javax.swing.GroupLayout(pnlActiv);
        pnlActiv.setLayout(pnlActivLayout);
        pnlActivLayout.setHorizontalGroup(
            pnlActivLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 30, Short.MAX_VALUE)
        );
        pnlActivLayout.setVerticalGroup(
            pnlActivLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 15, Short.MAX_VALUE)
        );

        lblActiv.setBackground(new java.awt.Color(0, 0, 0));
        lblActiv.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        lblActiv.setForeground(new java.awt.Color(255, 255, 255));
        lblActiv.setText("Стан підключення");

        lblRegister.setBackground(new java.awt.Color(255, 255, 255));
        lblRegister.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        lblRegister.setForeground(new java.awt.Color(255, 255, 255));
        lblRegister.setText("Не маєте аккаунту? Клікайте сюди для реєстрації");
        lblRegister.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblRegisterMouseClicked(evt);
            }
        });

        lblPib.setBackground(new java.awt.Color(255, 255, 255));
        lblPib.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        lblPib.setForeground(new java.awt.Color(255, 255, 255));
        lblPib.setText("ПІБ");

        txtPib.setBackground(new java.awt.Color(0, 0, 102));
        txtPib.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        txtPib.setForeground(new java.awt.Color(255, 255, 255));
        txtPib.setBorder(null);
        txtPib.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPibActionPerformed(evt);
            }
        });

        jSeparator4.setBackground(new java.awt.Color(255, 255, 255));
        jSeparator4.setForeground(new java.awt.Color(255, 0, 204));
        jSeparator4.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jSeparator4.setDebugGraphicsOptions(javax.swing.DebugGraphics.NONE_OPTION);
        jSeparator4.setFont(new java.awt.Font("Dialog", 0, 48)); // NOI18N

        btnUpdateCon.setBackground(new java.awt.Color(0, 0, 102));
        btnUpdateCon.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N
        btnUpdateCon.setForeground(new java.awt.Color(255, 255, 255));
        btnUpdateCon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Photo/square.png"))); // NOI18N
        btnUpdateCon.setText("Повторити");
        btnUpdateCon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateConActionPerformed(evt);
            }
        });

        btnBack.setBackground(new java.awt.Color(0, 0, 102));
        btnBack.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N
        btnBack.setForeground(new java.awt.Color(255, 255, 255));
        btnBack.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Photo/back-arrow.png"))); // NOI18N
        btnBack.setText("Назад");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        lblTitle.setBackground(new java.awt.Color(255, 255, 255));
        lblTitle.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        lblTitle.setForeground(new java.awt.Color(255, 255, 255));
        lblTitle.setText("Авторизація");

        jPanel1.setBackground(new java.awt.Color(0, 51, 204));

        btnSet.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Photo/gear (2).png"))); // NOI18N
        btnSet.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnSetMouseClicked(evt);
            }
        });

        btnHide.setIcon(new javax.swing.ImageIcon("C:\\Users\\7heXiMiK\\Desktop\\Covid-19\\Practice\\src\\Photo\\hide (1).png")); // NOI18N
        btnHide.setContentAreaFilled(false);
        btnHide.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnHideMouseClicked(evt);
            }
        });
        btnHide.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHideActionPerformed(evt);
            }
        });

        btnExit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Photo/logout.png"))); // NOI18N
        btnExit.setContentAreaFilled(false);
        btnExit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnExitMouseEntered(evt);
            }
        });
        btnExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExitActionPerformed(evt);
            }
        });

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Photo/business-and-finance.png"))); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnSet)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 289, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(btnHide, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnExit, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(13, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(64, 64, 64)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 268, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(193, 193, 193)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnHide, javax.swing.GroupLayout.DEFAULT_SIZE, 52, Short.MAX_VALUE)
                    .addComponent(btnSet, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnExit, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        javax.swing.GroupLayout pnlBodyLayout = new javax.swing.GroupLayout(pnlBody);
        pnlBody.setLayout(pnlBodyLayout);
        pnlBodyLayout.setHorizontalGroup(
            pnlBodyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlBodyLayout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(pnlBodyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlBodyLayout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addComponent(btnBack, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(38, 38, 38)
                        .addComponent(btnUpdateCon))
                    .addGroup(pnlBodyLayout.createSequentialGroup()
                        .addGap(86, 86, 86)
                        .addComponent(lblActiv)
                        .addGap(18, 18, 18)
                        .addComponent(pnlActiv, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnlBodyLayout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addGroup(pnlBodyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jSeparator1)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlBodyLayout.createSequentialGroup()
                                .addComponent(lblPass)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtPass, javax.swing.GroupLayout.PREFERRED_SIZE, 251, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jSeparator2, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlBodyLayout.createSequentialGroup()
                                .addComponent(lblLogin)
                                .addGap(18, 18, 18)
                                .addComponent(txtLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 254, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jSeparator4, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlBodyLayout.createSequentialGroup()
                                .addComponent(lblPib)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(txtPib, javax.swing.GroupLayout.PREFERRED_SIZE, 258, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlBodyLayout.createSequentialGroup()
                                .addComponent(lblTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(31, 31, 31))))
                    .addGroup(pnlBodyLayout.createSequentialGroup()
                        .addGap(58, 58, 58)
                        .addComponent(btnLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 238, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnlBodyLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblRegister, javax.swing.GroupLayout.PREFERRED_SIZE, 331, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(42, Short.MAX_VALUE))
        );
        pnlBodyLayout.setVerticalGroup(
            pnlBodyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlBodyLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(pnlBodyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtPib, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblPib))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlBodyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblLogin))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlBodyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtPass, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblPass))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lblRegister, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(pnlBodyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnUpdateCon)
                    .addComponent(btnBack, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(36, 36, 36)
                .addGroup(pnlBodyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblActiv)
                    .addComponent(pnlActiv, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(14, 14, 14))
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlBody, javax.swing.GroupLayout.DEFAULT_SIZE, 731, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlBody, javax.swing.GroupLayout.DEFAULT_SIZE, 583, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtLoginActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtLoginActionPerformed

    private void btnSetMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSetMouseClicked
        Open con = new Open();
        try {
            con.Read();
        } catch (IOException ex) {
            Logger.getLogger(Authorization.class.getName()).log(Level.SEVERE, null, ex);
        }
        con.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnSetMouseClicked
    /**
     * Зчитування даних для підкобчення
     *
     * @throws IOException
     */
    private void start() throws IOException {
        btnExit.setToolTipText("Вихід");
        btnHide.setToolTipText("Згорнути");
        btnSet.setToolTipText("Налаштування");
        this.setLocationRelativeTo(null);//center screen
        txtPib.setHorizontalAlignment(txtPib.CENTER);
        txtLogin.setHorizontalAlignment(txtLogin.CENTER);
        txtPass.setHorizontalAlignment(txtPass.CENTER);
        MoveMouseListener mml = new MoveMouseListener(pnlBody, this);
        pnlBody.addMouseListener(mml);
        pnlBody.addMouseMotionListener(mml);
        lblPib.setVisible(false);
        txtPib.setVisible(false);
        jSeparator4.setVisible(false);
        btnUpdateCon.setVisible(false);
        btnBack.setVisible(false);
        File f = new File("UserSettings.txt");
        if (f.exists() && !f.isDirectory()) {

        } else {
            FileWriter nFile = new FileWriter("UserSettings.txt");
            nFile.write("127.0.0.1" + "\n");
            nFile.write("3306" + "\n");
            nFile.write("ximik" + "\n");
            nFile.write("ximik69" + "\n");
            nFile.write("personality" + "\n");
            nFile.close();
        }
    }

    /**
     * Вхід або реєстрація
     */
    private void btnLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLoginActionPerformed
        DB a= new DB();
        if (reg == 0) {
            try {
                ResultSet rs = doQueryPreparedStatement();
                if (rs.first()) {
                    String name = rs.getString("PIB");
                    if ("ximik".equals(txtLogin.getText()) && "ximik".equals(txtPass.getText())) {
                        dispose();
                        JOptionPane.showMessageDialog(rootPane, "Вітаю Батьку");
                        m.setPIB(name);
                        m = new MainMenu();
                        m.setVisible(true);
                        
                    } else {
                        JOptionPane.showMessageDialog(rootPane, "Успішно.");
                        dispose();
                        m.setPIB(name);
                        m = new MainMenu();
                        m.setVisible(true);
                    }

                } else {
                    System.out.println(rs.first());
                    JOptionPane.showMessageDialog(rootPane, "Користувача з введеними даними не знайдено.");
                }
            } catch (SQLException ex) {
                Logger.getLogger(Authorization.class.getName()).log(Level.SEVERE, null, ex);
            }
        } else {
            //DB a = new DB();
            if (txtPib.getText().trim().length() <= 0 || txtLogin.getText().trim().length() <= 0 || txtPass.getText().trim().length() <= 0) {
                JOptionPane.showMessageDialog(rootPane, "Ведіть коректні дані");
            } else {
                if (txtPib.getText().trim().length() <= 150 || txtLogin.getText().trim().length() <= 150 || txtPass.getText().trim().length() <= 150) {
                    a.GetInfo("login", "users", txtLogin.getText());
                    if (a.getAddName() == "Такого нема") {
                        a.insert(txtPib.getText(), txtLogin.getText(), txtPass.getText());
                        JOptionPane.showMessageDialog(rootPane, "Успішно");
                        reg = 0;
                        txtPib.setText("");
                        btnLogin.setText("Увійти");
                        lblRegister.setVisible(false);
                        lblPib.setVisible(false);
                        txtPib.setVisible(false);
                        jSeparator4.setVisible(false);
                        txtLogin.setText("");
                        txtPass.setText("");
                        lblRegister.setVisible(true);
                        btnBack.setVisible(false);
                        lblTitle.setText("Авторизація");
                        //v.setVisible(true);
                        //this.setVisible(false);
                        PlugIn();
                        
                    } else {

                        JOptionPane.showMessageDialog(rootPane, "Такий логін існує");
                    }
                } else {
                    JOptionPane.showMessageDialog(rootPane, "Веедено багато символів, повторіть спробу");
                }
            }
        }
    }//GEN-LAST:event_btnLoginActionPerformed
    /**
     * Вихід
     *
     * @param evt
     */
    private void btnExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExitActionPerformed
        if (reg == 3) {
            dispose();
            // v.Use();
        } else {
            System.exit(0);
        }
    }//GEN-LAST:event_btnExitActionPerformed
    /**
     * Згортання вікна
     *
     * @param evt
     */
    private void btnHideActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHideActionPerformed
        this.setState(this.ICONIFIED);
    }//GEN-LAST:event_btnHideActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed

    private void pnlBodyMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlBodyMouseEntered

    }//GEN-LAST:event_pnlBodyMouseEntered

    private void formMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseEntered

    }//GEN-LAST:event_formMouseEntered

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        PlugIn();
    }//GEN-LAST:event_formWindowOpened

    private void btnExitMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnExitMouseEntered

    }//GEN-LAST:event_btnExitMouseEntered

    private void lblRegisterMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblRegisterMouseClicked
        lblTitle.setText("Реєстрація");
        lblRegister.setVisible(false);
        lblPib.setVisible(true);
        txtPib.setVisible(true);
        jSeparator4.setVisible(true);
        btnLogin.setText("Реєстрація");
        reg = 1;
        btnBack.setVisible(true);
        txtLogin.setText("");
        txtPass.setText("");
    }//GEN-LAST:event_lblRegisterMouseClicked
    /**
     * Редагування
     */
    void editUser() {
        btnSet.setVisible(false);
        btnLogin.setText("Застосувати");
        lblRegister.setVisible(false);
        lblPib.setVisible(true);
        txtPib.setVisible(true);
        jSeparator4.setVisible(true);
        lblTitle.setText("Редагування");
        //txtPib.setText(v.getName());
        // txtLogin.setText(v.getBiog());
        // txtPass.setText(v.getRel());
        reg = 3;
    }
    private void txtPibActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPibActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPibActionPerformed

    private void btnUpdateConActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateConActionPerformed
        PlugIn();
    }//GEN-LAST:event_btnUpdateConActionPerformed
    /**
     * Повернутись від реєстрації до входу
     *
     * @param evt
     */
    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        reg = 0;
        lblTitle.setText("Авторизація");
        btnBack.setVisible(false);
        btnLogin.setText("Увійти");
        lblRegister.setVisible(false);
        lblPib.setVisible(false);
        txtPib.setVisible(false);
        jSeparator4.setVisible(false);
        txtLogin.setText("");
        txtPass.setText("");
        lblRegister.setVisible(true);

    }//GEN-LAST:event_btnBackActionPerformed

    private void btnHideMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnHideMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_btnHideMouseClicked
    /**
     * Процедура вибірки даних для входу
     *
     * @return rs
     */
    private ResultSet doQueryPreparedStatement() {
        //DB a = new DB();
        String SQL = "SELECT * FROM users"+ " WHERE `login`=? AND `password`=? ";
        ResultSet rs = null;
        try {
            PreparedStatement stm = conn.prepareStatement(SQL);
            stm.setString(1, txtLogin.getText());
            stm.setString(2, txtPass.getText());
            rs = stm.executeQuery();
        } catch (SQLException ex) {
            Logger.getLogger(Authorization.class.getName()).log(Level.SEVERE, null, ex);
        }
        return rs;
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Authorization.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Authorization.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Authorization.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Authorization.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Authorization().setVisible(true);
            }
        });
    }

    public void Use() {
        this.setVisible(true);
        DB d = new DB();
        d.Connect();
    }

    void PlugIn() {
        DB a = new DB();
         conn = a.Connect();
            if (conn == null){
                pnlActiv.setBackground(Color.red);
                btnUpdateCon.setVisible(true);
                btnLogin.setEnabled(false);
                txtLogin.setEditable(false);
                txtPass.setEditable(false);
                txtPib.setEditable(false);
                return;
            } else {
                pnlActiv.setBackground(Color.GREEN);
                btnUpdateCon.setVisible(false);
                btnLogin.setEnabled(true);
                txtLogin.setEditable(true);
                txtPass.setEditable(true);
                txtPib.setEditable(true);
            }
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnExit;
    private javax.swing.JButton btnHide;
    private javax.swing.JButton btnLogin;
    private javax.swing.JLabel btnSet;
    private javax.swing.JButton btnUpdateCon;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JLabel lblActiv;
    private javax.swing.JLabel lblLogin;
    private javax.swing.JLabel lblLogin1;
    private javax.swing.JLabel lblPass;
    private javax.swing.JLabel lblPib;
    private javax.swing.JLabel lblRegister;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JPanel pnlActiv;
    private javax.swing.JPanel pnlBody;
    private javax.swing.JTextField txtLogin;
    private javax.swing.JTextField txtPass;
    private javax.swing.JTextField txtPib;
    // End of variables declaration//GEN-END:variables
}
