/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import java.awt.Color;
import java.io.File;
import java.io.IOException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.ImageIO;
import javax.swing.JButton;
import javax.swing.JComboBox;

/**
 *
 * @author 7heXiMiK
 */
public class BotCount extends javax.swing.JFrame {

    /**
     * @return the nameMap
     */
    public static String getNameMap() {
        return nameMap;
    }

    /**
     * @param aNameMap the nameMap to set
     */
    public static void setNameMap(String aNameMap) {
        nameMap = aNameMap;
    }

    /**
     * @return the botCoutn
     */
    public static int getBotCoutn() {
        return botCoutn;
    }

    /**
     * @param aBotCoutn the botCoutn to set
     */
    public static void setBotCoutn(int aBotCoutn) {
        botCoutn = aBotCoutn;
    }
    static int botCoutn = 1;
    private static String nameMap = "";
    public static ArrayList<String> mapList = new ArrayList<String>();
    public static ArrayList <String> programList=new ArrayList<>();
    /**
     * Creates new form BotCount
     */
    public BotCount() {
        initComponents();
        pnlColor1.setBackground(Color.BLUE);
        pnlColor2.setBackground(Color.RED);
        pnlColor3.setBackground(Color.YELLOW);
        pnlColor4.setBackground(Color.ORANGE);
        pnlColor5.setBackground(Color.GREEN);
        pnlColor6.setBackground(Color.PINK);
        pnlColor7.setBackground(Color.MAGENTA);
        pnlColor8.setBackground(Color.BLACK);
        MoveMouseListener mml = new MoveMouseListener(pnlHead, this);
        pnlHead.addMouseListener(mml);
        pnlHead.addMouseMotionListener(mml);
        File IconForm = new File("Photo/labyrinth.png");
        try {
            this.setIconImage(ImageIO.read(IconForm));
        } catch (IOException ex) {
            Logger.getLogger(Authorization.class.getName()).log(Level.SEVERE, null, ex);
        }
        mapList.clear();
        getBotInstrList();
        
        for (int i = 0; i < mapList.size(); i++) {
            jCBSet1.addItem(mapList.get(i));
            jCBSet2.addItem(mapList.get(i));
            jCBSet3.addItem(mapList.get(i));
            jCBSet4.addItem(mapList.get(i));
            jCBSet5.addItem(mapList.get(i));
            jCBSet6.addItem(mapList.get(i));
            jCBSet7.addItem(mapList.get(i));
            jCBSet8.addItem(mapList.get(i));
        }
        int Width = this.getWidth() - 10;
        int Height = this.getHeight();
        int btnX = btnNext.getX();
        int btnY = btnNext.getY();
        if (getBotCoutn() == 1) {
            this.setSize(Width - 880, Height);
        } else if (getBotCoutn() == 2) {
            this.setSize(Width - 750, Height);
        } else if (getBotCoutn() == 3) {
            this.setSize(Width - 620, Height);
        } else if (getBotCoutn() == 4) {
            this.setSize(Width - 495, Height);
        } else if (getBotCoutn() == 5) {
            this.setSize(Width - 365, Height);
        } else if (getBotCoutn() == 6) {
            this.setSize(Width - 240, Height);
        } else if (getBotCoutn() == 7) {
            this.setSize(Width - 115, Height);
        } else if (getBotCoutn() == 8) {
        }

        this.setLocationRelativeTo(null);//center screen
    }

    public static void getBotInstrList() {
        String map = ("res/botPrograms/");
        System.out.println("old api:");
        File directory = new File(map);
        
        for (File e : directory.listFiles()) {
            
            if (e.isFile()) {
                System.out.print("  ");
                System.out.println(e.getName());
                mapList.add(e.getName());
                

            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlBody = new javax.swing.JPanel();
        pnlHead = new javax.swing.JPanel();
        btnHide = new javax.swing.JButton();
        btnExit = new javax.swing.JButton();
        pnlBot1 = new javax.swing.JPanel();
        lblBot1 = new javax.swing.JLabel();
        lblColor1 = new javax.swing.JLabel();
        pnlColor1 = new javax.swing.JPanel();
        lblSet1 = new javax.swing.JLabel();
        lblSet2 = new javax.swing.JLabel();
        jCBSet1 = new javax.swing.JComboBox<>();
        pnlBot2 = new javax.swing.JPanel();
        lblBot2 = new javax.swing.JLabel();
        lblColor2 = new javax.swing.JLabel();
        pnlColor2 = new javax.swing.JPanel();
        lblSet3 = new javax.swing.JLabel();
        lblSet4 = new javax.swing.JLabel();
        jCBSet2 = new javax.swing.JComboBox<>();
        pnlBot3 = new javax.swing.JPanel();
        lblBot3 = new javax.swing.JLabel();
        lblColor3 = new javax.swing.JLabel();
        pnlColor3 = new javax.swing.JPanel();
        lblSet5 = new javax.swing.JLabel();
        lblSet6 = new javax.swing.JLabel();
        jCBSet3 = new javax.swing.JComboBox<>();
        pnlBot4 = new javax.swing.JPanel();
        lblBot4 = new javax.swing.JLabel();
        lblColor4 = new javax.swing.JLabel();
        pnlColor4 = new javax.swing.JPanel();
        lblSet7 = new javax.swing.JLabel();
        lblSet8 = new javax.swing.JLabel();
        jCBSet4 = new javax.swing.JComboBox<>();
        pnlBot5 = new javax.swing.JPanel();
        lblBot5 = new javax.swing.JLabel();
        lblColor5 = new javax.swing.JLabel();
        pnlColor5 = new javax.swing.JPanel();
        lblSet9 = new javax.swing.JLabel();
        lblSet10 = new javax.swing.JLabel();
        jCBSet5 = new javax.swing.JComboBox<>();
        pnlBot6 = new javax.swing.JPanel();
        lblBot6 = new javax.swing.JLabel();
        lblColor6 = new javax.swing.JLabel();
        pnlColor6 = new javax.swing.JPanel();
        lblSet11 = new javax.swing.JLabel();
        lblSet12 = new javax.swing.JLabel();
        jCBSet6 = new javax.swing.JComboBox<>();
        pnlBot7 = new javax.swing.JPanel();
        lblBot7 = new javax.swing.JLabel();
        lblColor7 = new javax.swing.JLabel();
        pnlColor7 = new javax.swing.JPanel();
        lblSet13 = new javax.swing.JLabel();
        lblSet14 = new javax.swing.JLabel();
        jCBSet7 = new javax.swing.JComboBox<>();
        pnlBot8 = new javax.swing.JPanel();
        lblBot8 = new javax.swing.JLabel();
        lblColor8 = new javax.swing.JLabel();
        pnlColor8 = new javax.swing.JPanel();
        lblSet15 = new javax.swing.JLabel();
        lblSet16 = new javax.swing.JLabel();
        jCBSet8 = new javax.swing.JComboBox<>();
        btnNext = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        pnlBody.setBackground(new java.awt.Color(0, 0, 102));

        pnlHead.setBackground(new java.awt.Color(0, 51, 204));

        btnHide.setIcon(new javax.swing.ImageIcon("C:\\Users\\7heXiMiK\\Desktop\\Covid-19\\Practice\\src\\Photo\\hide (1).png")); // NOI18N
        btnHide.setContentAreaFilled(false);
        btnHide.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnHideMouseClicked(evt);
            }
        });
        btnHide.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHideActionPerformed(evt);
            }
        });

        btnExit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Photo/logout.png"))); // NOI18N
        btnExit.setContentAreaFilled(false);
        btnExit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnExitMouseEntered(evt);
            }
        });
        btnExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExitActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlHeadLayout = new javax.swing.GroupLayout(pnlHead);
        pnlHead.setLayout(pnlHeadLayout);
        pnlHeadLayout.setHorizontalGroup(
            pnlHeadLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlHeadLayout.createSequentialGroup()
                .addGap(4, 4, 4)
                .addComponent(btnExit, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnHide, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnlHeadLayout.setVerticalGroup(
            pnlHeadLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnHide, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(btnExit, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pnlBot1.setBackground(new java.awt.Color(0, 51, 204));
        pnlBot1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                pnlBot1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                pnlBot1MouseExited(evt);
            }
        });

        lblBot1.setBackground(new java.awt.Color(255, 255, 255));
        lblBot1.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        lblBot1.setForeground(new java.awt.Color(255, 255, 255));
        lblBot1.setText("Гравець 1");

        lblColor1.setBackground(new java.awt.Color(255, 255, 255));
        lblColor1.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        lblColor1.setForeground(new java.awt.Color(255, 255, 255));
        lblColor1.setText("Колір");

        pnlColor1.setBackground(new java.awt.Color(255, 20, 147));

        javax.swing.GroupLayout pnlColor1Layout = new javax.swing.GroupLayout(pnlColor1);
        pnlColor1.setLayout(pnlColor1Layout);
        pnlColor1Layout.setHorizontalGroup(
            pnlColor1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 42, Short.MAX_VALUE)
        );
        pnlColor1Layout.setVerticalGroup(
            pnlColor1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        lblSet1.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        lblSet1.setForeground(new java.awt.Color(255, 255, 255));
        lblSet1.setText("Налаштування");

        lblSet2.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        lblSet2.setForeground(new java.awt.Color(255, 255, 255));
        lblSet2.setText("Гравця");

        jCBSet1.setBackground(new java.awt.Color(0, 0, 102));
        jCBSet1.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jCBSet1.setForeground(new java.awt.Color(255, 255, 255));
        jCBSet1.setName(""); // NOI18N
        jCBSet1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jCBSet1MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jCBSet1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jCBSet1MouseExited(evt);
            }
        });

        javax.swing.GroupLayout pnlBot1Layout = new javax.swing.GroupLayout(pnlBot1);
        pnlBot1.setLayout(pnlBot1Layout);
        pnlBot1Layout.setHorizontalGroup(
            pnlBot1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlBot1Layout.createSequentialGroup()
                .addGroup(pnlBot1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlBot1Layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addComponent(lblBot1))
                    .addGroup(pnlBot1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lblColor1)
                        .addGap(18, 18, 18)
                        .addComponent(pnlColor1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnlBot1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lblSet1)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(jCBSet1, javax.swing.GroupLayout.Alignment.TRAILING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlBot1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(lblSet2)
                .addGap(30, 30, 30))
        );
        pnlBot1Layout.setVerticalGroup(
            pnlBot1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlBot1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblBot1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlBot1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(pnlColor1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblColor1, javax.swing.GroupLayout.DEFAULT_SIZE, 32, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblSet1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblSet2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jCBSet1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pnlBot2.setBackground(new java.awt.Color(0, 51, 204));
        pnlBot2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                pnlBot2MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                pnlBot2MouseExited(evt);
            }
        });

        lblBot2.setBackground(new java.awt.Color(255, 255, 255));
        lblBot2.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        lblBot2.setForeground(new java.awt.Color(255, 255, 255));
        lblBot2.setText("Гравець 2");

        lblColor2.setBackground(new java.awt.Color(255, 255, 255));
        lblColor2.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        lblColor2.setForeground(new java.awt.Color(255, 255, 255));
        lblColor2.setText("Колір");

        pnlColor2.setBackground(new java.awt.Color(255, 165, 0));

        javax.swing.GroupLayout pnlColor2Layout = new javax.swing.GroupLayout(pnlColor2);
        pnlColor2.setLayout(pnlColor2Layout);
        pnlColor2Layout.setHorizontalGroup(
            pnlColor2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 42, Short.MAX_VALUE)
        );
        pnlColor2Layout.setVerticalGroup(
            pnlColor2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        lblSet3.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        lblSet3.setForeground(new java.awt.Color(255, 255, 255));
        lblSet3.setText("Налаштування");

        lblSet4.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        lblSet4.setForeground(new java.awt.Color(255, 255, 255));
        lblSet4.setText("Гравця");

        jCBSet2.setBackground(new java.awt.Color(0, 0, 102));
        jCBSet2.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jCBSet2.setForeground(new java.awt.Color(255, 255, 255));
        jCBSet2.setName(""); // NOI18N
        jCBSet2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jCBSet2MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jCBSet2MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jCBSet2MouseExited(evt);
            }
        });

        javax.swing.GroupLayout pnlBot2Layout = new javax.swing.GroupLayout(pnlBot2);
        pnlBot2.setLayout(pnlBot2Layout);
        pnlBot2Layout.setHorizontalGroup(
            pnlBot2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlBot2Layout.createSequentialGroup()
                .addGroup(pnlBot2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlBot2Layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addComponent(lblBot2)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(pnlBot2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lblColor2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(pnlColor2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlBot2Layout.createSequentialGroup()
                        .addGap(0, 6, Short.MAX_VALUE)
                        .addComponent(lblSet3)))
                .addContainerGap())
            .addComponent(jCBSet2, javax.swing.GroupLayout.Alignment.TRAILING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(pnlBot2Layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(lblSet4)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnlBot2Layout.setVerticalGroup(
            pnlBot2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlBot2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblBot2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlBot2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(pnlColor2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblColor2, javax.swing.GroupLayout.DEFAULT_SIZE, 32, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblSet3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblSet4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jCBSet2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pnlBot3.setBackground(new java.awt.Color(0, 51, 204));
        pnlBot3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                pnlBot3MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                pnlBot3MouseExited(evt);
            }
        });

        lblBot3.setBackground(new java.awt.Color(255, 255, 255));
        lblBot3.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        lblBot3.setForeground(new java.awt.Color(255, 255, 255));
        lblBot3.setText("Гравець 3");

        lblColor3.setBackground(new java.awt.Color(255, 255, 255));
        lblColor3.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        lblColor3.setForeground(new java.awt.Color(255, 255, 255));
        lblColor3.setText("Колір");

        pnlColor3.setBackground(new java.awt.Color(75, 0, 130));

        javax.swing.GroupLayout pnlColor3Layout = new javax.swing.GroupLayout(pnlColor3);
        pnlColor3.setLayout(pnlColor3Layout);
        pnlColor3Layout.setHorizontalGroup(
            pnlColor3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 42, Short.MAX_VALUE)
        );
        pnlColor3Layout.setVerticalGroup(
            pnlColor3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        lblSet5.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        lblSet5.setForeground(new java.awt.Color(255, 255, 255));
        lblSet5.setText("Налаштування");

        lblSet6.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        lblSet6.setForeground(new java.awt.Color(255, 255, 255));
        lblSet6.setText("Гравця");

        jCBSet3.setBackground(new java.awt.Color(0, 0, 102));
        jCBSet3.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jCBSet3.setForeground(new java.awt.Color(255, 255, 255));
        jCBSet3.setName(""); // NOI18N
        jCBSet3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jCBSet3MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jCBSet3MouseExited(evt);
            }
        });

        javax.swing.GroupLayout pnlBot3Layout = new javax.swing.GroupLayout(pnlBot3);
        pnlBot3.setLayout(pnlBot3Layout);
        pnlBot3Layout.setHorizontalGroup(
            pnlBot3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlBot3Layout.createSequentialGroup()
                .addGroup(pnlBot3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlBot3Layout.createSequentialGroup()
                        .addGroup(pnlBot3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnlBot3Layout.createSequentialGroup()
                                .addGap(25, 25, 25)
                                .addComponent(lblBot3))
                            .addGroup(pnlBot3Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(lblColor3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(pnlColor3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlBot3Layout.createSequentialGroup()
                        .addGap(0, 6, Short.MAX_VALUE)
                        .addComponent(lblSet5)))
                .addContainerGap())
            .addComponent(jCBSet3, javax.swing.GroupLayout.Alignment.TRAILING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(pnlBot3Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(lblSet6)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnlBot3Layout.setVerticalGroup(
            pnlBot3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlBot3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblBot3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlBot3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(pnlColor3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblColor3, javax.swing.GroupLayout.DEFAULT_SIZE, 32, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblSet5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblSet6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jCBSet3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(16, Short.MAX_VALUE))
        );

        pnlBot4.setBackground(new java.awt.Color(0, 51, 204));
        pnlBot4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                pnlBot4MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                pnlBot4MouseExited(evt);
            }
        });

        lblBot4.setBackground(new java.awt.Color(255, 255, 255));
        lblBot4.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        lblBot4.setForeground(new java.awt.Color(255, 255, 255));
        lblBot4.setText("Гравець 4");

        lblColor4.setBackground(new java.awt.Color(255, 255, 255));
        lblColor4.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        lblColor4.setForeground(new java.awt.Color(255, 255, 255));
        lblColor4.setText("Колір");

        pnlColor4.setBackground(new java.awt.Color(205, 92, 92));

        javax.swing.GroupLayout pnlColor4Layout = new javax.swing.GroupLayout(pnlColor4);
        pnlColor4.setLayout(pnlColor4Layout);
        pnlColor4Layout.setHorizontalGroup(
            pnlColor4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 42, Short.MAX_VALUE)
        );
        pnlColor4Layout.setVerticalGroup(
            pnlColor4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        lblSet7.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        lblSet7.setForeground(new java.awt.Color(255, 255, 255));
        lblSet7.setText("Налаштування");

        lblSet8.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        lblSet8.setForeground(new java.awt.Color(255, 255, 255));
        lblSet8.setText("Гравця");

        jCBSet4.setBackground(new java.awt.Color(0, 0, 102));
        jCBSet4.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jCBSet4.setForeground(new java.awt.Color(255, 255, 255));
        jCBSet4.setName(""); // NOI18N
        jCBSet4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jCBSet4MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jCBSet4MouseExited(evt);
            }
        });

        javax.swing.GroupLayout pnlBot4Layout = new javax.swing.GroupLayout(pnlBot4);
        pnlBot4.setLayout(pnlBot4Layout);
        pnlBot4Layout.setHorizontalGroup(
            pnlBot4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jCBSet4, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(pnlBot4Layout.createSequentialGroup()
                .addGroup(pnlBot4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlBot4Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lblColor4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(pnlColor4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnlBot4Layout.createSequentialGroup()
                        .addGroup(pnlBot4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnlBot4Layout.createSequentialGroup()
                                .addGap(27, 27, 27)
                                .addComponent(lblBot4))
                            .addGroup(pnlBot4Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(lblSet7)))
                        .addGap(0, 2, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlBot4Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(lblSet8)
                .addGap(31, 31, 31))
        );
        pnlBot4Layout.setVerticalGroup(
            pnlBot4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlBot4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblBot4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlBot4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(pnlColor4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblColor4, javax.swing.GroupLayout.DEFAULT_SIZE, 32, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblSet7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblSet8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jCBSet4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pnlBot5.setBackground(new java.awt.Color(0, 51, 204));
        pnlBot5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                pnlBot5MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                pnlBot5MouseExited(evt);
            }
        });

        lblBot5.setBackground(new java.awt.Color(255, 255, 255));
        lblBot5.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        lblBot5.setForeground(new java.awt.Color(255, 255, 255));
        lblBot5.setText("Гравець 5 ");

        lblColor5.setBackground(new java.awt.Color(255, 255, 255));
        lblColor5.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        lblColor5.setForeground(new java.awt.Color(255, 255, 255));
        lblColor5.setText("Колір");

        pnlColor5.setBackground(new java.awt.Color(0, 255, 255));

        javax.swing.GroupLayout pnlColor5Layout = new javax.swing.GroupLayout(pnlColor5);
        pnlColor5.setLayout(pnlColor5Layout);
        pnlColor5Layout.setHorizontalGroup(
            pnlColor5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 42, Short.MAX_VALUE)
        );
        pnlColor5Layout.setVerticalGroup(
            pnlColor5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        lblSet9.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        lblSet9.setForeground(new java.awt.Color(255, 255, 255));
        lblSet9.setText("Налаштування");

        lblSet10.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        lblSet10.setForeground(new java.awt.Color(255, 255, 255));
        lblSet10.setText("Гравця");

        jCBSet5.setBackground(new java.awt.Color(0, 0, 102));
        jCBSet5.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jCBSet5.setForeground(new java.awt.Color(255, 255, 255));
        jCBSet5.setName(""); // NOI18N
        jCBSet5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jCBSet5MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jCBSet5MouseExited(evt);
            }
        });

        javax.swing.GroupLayout pnlBot5Layout = new javax.swing.GroupLayout(pnlBot5);
        pnlBot5.setLayout(pnlBot5Layout);
        pnlBot5Layout.setHorizontalGroup(
            pnlBot5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlBot5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlBot5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlBot5Layout.createSequentialGroup()
                        .addComponent(lblColor5)
                        .addGap(18, 18, 18)
                        .addComponent(pnlColor5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlBot5Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(pnlBot5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlBot5Layout.createSequentialGroup()
                                .addComponent(lblBot5)
                                .addGap(28, 28, 28))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlBot5Layout.createSequentialGroup()
                                .addComponent(lblSet9)
                                .addContainerGap())))))
            .addComponent(jCBSet5, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(pnlBot5Layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(lblSet10)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        pnlBot5Layout.setVerticalGroup(
            pnlBot5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlBot5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblBot5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlBot5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(pnlColor5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblColor5, javax.swing.GroupLayout.DEFAULT_SIZE, 32, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblSet9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblSet10)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jCBSet5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pnlBot6.setBackground(new java.awt.Color(0, 51, 204));
        pnlBot6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                pnlBot6MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                pnlBot6MouseExited(evt);
            }
        });

        lblBot6.setBackground(new java.awt.Color(255, 255, 255));
        lblBot6.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        lblBot6.setForeground(new java.awt.Color(255, 255, 255));
        lblBot6.setText("Гравець 6");

        lblColor6.setBackground(new java.awt.Color(255, 255, 255));
        lblColor6.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        lblColor6.setForeground(new java.awt.Color(255, 255, 255));
        lblColor6.setText("Колір");

        pnlColor6.setBackground(new java.awt.Color(0, 255, 0));

        javax.swing.GroupLayout pnlColor6Layout = new javax.swing.GroupLayout(pnlColor6);
        pnlColor6.setLayout(pnlColor6Layout);
        pnlColor6Layout.setHorizontalGroup(
            pnlColor6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 42, Short.MAX_VALUE)
        );
        pnlColor6Layout.setVerticalGroup(
            pnlColor6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        lblSet11.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        lblSet11.setForeground(new java.awt.Color(255, 255, 255));
        lblSet11.setText("Налаштування");

        lblSet12.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        lblSet12.setForeground(new java.awt.Color(255, 255, 255));
        lblSet12.setText("Гравця");

        jCBSet6.setBackground(new java.awt.Color(0, 0, 102));
        jCBSet6.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jCBSet6.setForeground(new java.awt.Color(255, 255, 255));
        jCBSet6.setName(""); // NOI18N
        jCBSet6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jCBSet6MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jCBSet6MouseExited(evt);
            }
        });

        javax.swing.GroupLayout pnlBot6Layout = new javax.swing.GroupLayout(pnlBot6);
        pnlBot6.setLayout(pnlBot6Layout);
        pnlBot6Layout.setHorizontalGroup(
            pnlBot6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlBot6Layout.createSequentialGroup()
                .addGroup(pnlBot6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlBot6Layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addComponent(lblBot6)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(pnlBot6Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lblColor6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(pnlColor6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlBot6Layout.createSequentialGroup()
                        .addGap(0, 6, Short.MAX_VALUE)
                        .addComponent(lblSet11)))
                .addContainerGap())
            .addComponent(jCBSet6, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(pnlBot6Layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(lblSet12)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnlBot6Layout.setVerticalGroup(
            pnlBot6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlBot6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblBot6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlBot6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(pnlColor6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblColor6, javax.swing.GroupLayout.DEFAULT_SIZE, 32, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblSet11)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblSet12)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jCBSet6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pnlBot7.setBackground(new java.awt.Color(0, 51, 204));
        pnlBot7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                pnlBot7MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                pnlBot7MouseExited(evt);
            }
        });

        lblBot7.setBackground(new java.awt.Color(255, 255, 255));
        lblBot7.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        lblBot7.setForeground(new java.awt.Color(255, 255, 255));
        lblBot7.setText("Гравець 7");

        lblColor7.setBackground(new java.awt.Color(255, 255, 255));
        lblColor7.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        lblColor7.setForeground(new java.awt.Color(255, 255, 255));
        lblColor7.setText("Колір");

        pnlColor7.setBackground(new java.awt.Color(123, 104, 238));

        javax.swing.GroupLayout pnlColor7Layout = new javax.swing.GroupLayout(pnlColor7);
        pnlColor7.setLayout(pnlColor7Layout);
        pnlColor7Layout.setHorizontalGroup(
            pnlColor7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 42, Short.MAX_VALUE)
        );
        pnlColor7Layout.setVerticalGroup(
            pnlColor7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        lblSet13.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        lblSet13.setForeground(new java.awt.Color(255, 255, 255));
        lblSet13.setText("Налаштування");

        lblSet14.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        lblSet14.setForeground(new java.awt.Color(255, 255, 255));
        lblSet14.setText("Гравця");

        jCBSet7.setBackground(new java.awt.Color(0, 0, 102));
        jCBSet7.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jCBSet7.setForeground(new java.awt.Color(255, 255, 255));
        jCBSet7.setName(""); // NOI18N
        jCBSet7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jCBSet7MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jCBSet7MouseExited(evt);
            }
        });

        javax.swing.GroupLayout pnlBot7Layout = new javax.swing.GroupLayout(pnlBot7);
        pnlBot7.setLayout(pnlBot7Layout);
        pnlBot7Layout.setHorizontalGroup(
            pnlBot7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlBot7Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblBot7)
                .addGap(27, 27, 27))
            .addGroup(pnlBot7Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlBot7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlBot7Layout.createSequentialGroup()
                        .addComponent(lblColor7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(pnlColor7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnlBot7Layout.createSequentialGroup()
                        .addComponent(lblSet13)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addComponent(jCBSet7, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(pnlBot7Layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(lblSet14)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnlBot7Layout.setVerticalGroup(
            pnlBot7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlBot7Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblBot7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlBot7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(pnlColor7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblColor7, javax.swing.GroupLayout.DEFAULT_SIZE, 32, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblSet13)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblSet14)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jCBSet7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pnlBot8.setBackground(new java.awt.Color(0, 51, 204));
        pnlBot8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                pnlBot8MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                pnlBot8MouseExited(evt);
            }
        });

        lblBot8.setBackground(new java.awt.Color(255, 255, 255));
        lblBot8.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        lblBot8.setForeground(new java.awt.Color(255, 255, 255));
        lblBot8.setText("Гравець 8");

        lblColor8.setBackground(new java.awt.Color(255, 255, 255));
        lblColor8.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        lblColor8.setForeground(new java.awt.Color(255, 255, 255));
        lblColor8.setText("Колір");

        pnlColor8.setBackground(new java.awt.Color(220, 20, 60));

        javax.swing.GroupLayout pnlColor8Layout = new javax.swing.GroupLayout(pnlColor8);
        pnlColor8.setLayout(pnlColor8Layout);
        pnlColor8Layout.setHorizontalGroup(
            pnlColor8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 42, Short.MAX_VALUE)
        );
        pnlColor8Layout.setVerticalGroup(
            pnlColor8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        lblSet15.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        lblSet15.setForeground(new java.awt.Color(255, 255, 255));
        lblSet15.setText("Налаштування");

        lblSet16.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        lblSet16.setForeground(new java.awt.Color(255, 255, 255));
        lblSet16.setText("Гравця");

        jCBSet8.setBackground(new java.awt.Color(0, 0, 102));
        jCBSet8.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jCBSet8.setForeground(new java.awt.Color(255, 255, 255));
        jCBSet8.setName(""); // NOI18N
        jCBSet8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jCBSet8MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jCBSet8MouseExited(evt);
            }
        });

        javax.swing.GroupLayout pnlBot8Layout = new javax.swing.GroupLayout(pnlBot8);
        pnlBot8.setLayout(pnlBot8Layout);
        pnlBot8Layout.setHorizontalGroup(
            pnlBot8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jCBSet8, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(pnlBot8Layout.createSequentialGroup()
                .addGroup(pnlBot8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlBot8Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lblColor8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(pnlColor8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnlBot8Layout.createSequentialGroup()
                        .addGroup(pnlBot8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnlBot8Layout.createSequentialGroup()
                                .addGap(24, 24, 24)
                                .addComponent(lblBot8))
                            .addGroup(pnlBot8Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(lblSet15))
                            .addGroup(pnlBot8Layout.createSequentialGroup()
                                .addGap(31, 31, 31)
                                .addComponent(lblSet16)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        pnlBot8Layout.setVerticalGroup(
            pnlBot8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlBot8Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblBot8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlBot8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(pnlColor8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblColor8, javax.swing.GroupLayout.DEFAULT_SIZE, 32, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblSet15)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblSet16)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jCBSet8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(16, Short.MAX_VALUE))
        );

        btnNext.setBackground(new java.awt.Color(0, 51, 204));
        btnNext.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        btnNext.setForeground(new java.awt.Color(255, 255, 255));
        btnNext.setText("Продовжити");
        btnNext.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnNextMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnNextMouseExited(evt);
            }
        });
        btnNext.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNextActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlBodyLayout = new javax.swing.GroupLayout(pnlBody);
        pnlBody.setLayout(pnlBodyLayout);
        pnlBodyLayout.setHorizontalGroup(
            pnlBodyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlHead, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(pnlBodyLayout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addGroup(pnlBodyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnNext)
                    .addGroup(pnlBodyLayout.createSequentialGroup()
                        .addComponent(pnlBot1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(pnlBot2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(pnlBot3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(pnlBot4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(pnlBot5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(pnlBot6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(pnlBot7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(pnlBot8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnlBodyLayout.setVerticalGroup(
            pnlBodyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlBodyLayout.createSequentialGroup()
                .addComponent(pnlHead, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(pnlBodyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlBodyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(pnlBot1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(pnlBot2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(pnlBot4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(pnlBot5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(pnlBot7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(pnlBot6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(pnlBot8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(pnlBot3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnNext, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(14, 14, 14))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlBody, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlBody, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void pnlBot1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlBot1MouseEntered
        pnlBot1.setBackground(new Color(102, 0, 204));
    }//GEN-LAST:event_pnlBot1MouseEntered

    private void pnlBot1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlBot1MouseExited
        pnlBot1.setBackground(new Color(0, 51, 204));
    }//GEN-LAST:event_pnlBot1MouseExited

    private void jCBSet1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jCBSet1MouseEntered
        pnlBot1.setBackground(new Color(102, 0, 204));
    }//GEN-LAST:event_jCBSet1MouseEntered

    private void jCBSet1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jCBSet1MouseExited
        pnlBot1.setBackground(new Color(0, 51, 204));
    }//GEN-LAST:event_jCBSet1MouseExited

    private void jCBSet1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jCBSet1MouseClicked
        pnlBot1.setBackground(new Color(102, 0, 204));
    }//GEN-LAST:event_jCBSet1MouseClicked

    private void pnlBot2MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlBot2MouseEntered
        pnlBot2.setBackground(new Color(102, 0, 204));
    }//GEN-LAST:event_pnlBot2MouseEntered

    private void pnlBot2MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlBot2MouseExited
        pnlBot2.setBackground(new Color(0, 51, 204));
    }//GEN-LAST:event_pnlBot2MouseExited

    private void jCBSet2MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jCBSet2MouseEntered
        pnlBot2.setBackground(new Color(102, 0, 204));
    }//GEN-LAST:event_jCBSet2MouseEntered

    private void jCBSet2MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jCBSet2MouseExited
        pnlBot2.setBackground(new Color(0, 51, 204));
    }//GEN-LAST:event_jCBSet2MouseExited

    private void jCBSet2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jCBSet2MouseClicked
        pnlBot2.setBackground(new Color(102, 0, 204));
    }//GEN-LAST:event_jCBSet2MouseClicked

    private void pnlBot3MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlBot3MouseEntered
        pnlBot3.setBackground(new Color(102, 0, 204));
    }//GEN-LAST:event_pnlBot3MouseEntered

    private void pnlBot3MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlBot3MouseExited
        pnlBot3.setBackground(new Color(0, 51, 204));
    }//GEN-LAST:event_pnlBot3MouseExited

    private void jCBSet3MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jCBSet3MouseEntered
        pnlBot3.setBackground(new Color(102, 0, 204));
    }//GEN-LAST:event_jCBSet3MouseEntered

    private void jCBSet3MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jCBSet3MouseExited
        pnlBot3.setBackground(new Color(0, 51, 204));
    }//GEN-LAST:event_jCBSet3MouseExited

    private void pnlBot4MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlBot4MouseEntered
        pnlBot4.setBackground(new Color(102, 0, 204));
    }//GEN-LAST:event_pnlBot4MouseEntered

    private void pnlBot4MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlBot4MouseExited
        pnlBot4.setBackground(new Color(0, 51, 204));
    }//GEN-LAST:event_pnlBot4MouseExited

    private void jCBSet4MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jCBSet4MouseEntered
        pnlBot4.setBackground(new Color(102, 0, 204));
    }//GEN-LAST:event_jCBSet4MouseEntered

    private void jCBSet4MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jCBSet4MouseExited
        pnlBot4.setBackground(new Color(0, 51, 204));
    }//GEN-LAST:event_jCBSet4MouseExited

    private void pnlBot5MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlBot5MouseEntered
        pnlBot5.setBackground(new Color(102, 0, 204));
    }//GEN-LAST:event_pnlBot5MouseEntered

    private void pnlBot5MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlBot5MouseExited
        pnlBot5.setBackground(new Color(0, 51, 204));
    }//GEN-LAST:event_pnlBot5MouseExited

    private void jCBSet5MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jCBSet5MouseEntered
        pnlBot5.setBackground(new Color(102, 0, 204));
    }//GEN-LAST:event_jCBSet5MouseEntered

    private void jCBSet5MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jCBSet5MouseExited
        pnlBot5.setBackground(new Color(0, 51, 204));
    }//GEN-LAST:event_jCBSet5MouseExited

    private void pnlBot6MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlBot6MouseEntered
        pnlBot6.setBackground(new Color(102, 0, 204));
    }//GEN-LAST:event_pnlBot6MouseEntered

    private void pnlBot6MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlBot6MouseExited
        pnlBot6.setBackground(new Color(0, 51, 204));
    }//GEN-LAST:event_pnlBot6MouseExited

    private void jCBSet6MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jCBSet6MouseEntered
        pnlBot6.setBackground(new Color(102, 0, 204));
    }//GEN-LAST:event_jCBSet6MouseEntered

    private void jCBSet6MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jCBSet6MouseExited
        pnlBot6.setBackground(new Color(0, 51, 204));
    }//GEN-LAST:event_jCBSet6MouseExited

    private void pnlBot7MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlBot7MouseEntered
        pnlBot7.setBackground(new Color(102, 0, 204));
    }//GEN-LAST:event_pnlBot7MouseEntered

    private void pnlBot7MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlBot7MouseExited
        pnlBot7.setBackground(new Color(0, 51, 204));
    }//GEN-LAST:event_pnlBot7MouseExited

    private void jCBSet7MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jCBSet7MouseEntered
        pnlBot7.setBackground(new Color(102, 0, 204));
    }//GEN-LAST:event_jCBSet7MouseEntered

    private void jCBSet7MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jCBSet7MouseExited
        pnlBot7.setBackground(new Color(0, 51, 204));
    }//GEN-LAST:event_jCBSet7MouseExited

    private void pnlBot8MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlBot8MouseEntered
        pnlBot8.setBackground(new Color(102, 0, 204));
    }//GEN-LAST:event_pnlBot8MouseEntered

    private void pnlBot8MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlBot8MouseExited
        pnlBot8.setBackground(new Color(0, 51, 204));
    }//GEN-LAST:event_pnlBot8MouseExited

    private void jCBSet8MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jCBSet8MouseEntered
        pnlBot8.setBackground(new Color(102, 0, 204));
    }//GEN-LAST:event_jCBSet8MouseEntered

    private void jCBSet8MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jCBSet8MouseExited
        pnlBot8.setBackground(new Color(0, 51, 204));
    }//GEN-LAST:event_jCBSet8MouseExited

    private void btnNextMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnNextMouseEntered
        btnNext.setBackground(new Color(102, 0, 204));
    }//GEN-LAST:event_btnNextMouseEntered

    private void btnNextMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnNextMouseExited
        btnNext.setBackground(new Color(0, 51, 204));
    }//GEN-LAST:event_btnNextMouseExited

    private void btnHideMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnHideMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_btnHideMouseClicked

    private void btnHideActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHideActionPerformed
        this.setState(this.ICONIFIED);
    }//GEN-LAST:event_btnHideActionPerformed

    private void btnExitMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnExitMouseEntered

    }//GEN-LAST:event_btnExitMouseEntered

    private void btnExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExitActionPerformed
        dispose();
        MainMenu m = new MainMenu();
        m.setVisible(true);
        m = null;
    }//GEN-LAST:event_btnExitActionPerformed

    private void btnNextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNextActionPerformed

        try {
            dispose();
            Maze.setBotCount(getBotCoutn());
            System.out.println(jCBSet1.getSelectedItem().toString());
            programList.add(0, (jCBSet1.getSelectedItem()).toString());
            programList.add(1,(jCBSet2.getSelectedItem()).toString());
            programList.add(2,(jCBSet3.getSelectedItem()).toString());
            programList.add(3,(jCBSet4.getSelectedItem()).toString());
            programList.add(4,(jCBSet5.getSelectedItem()).toString());
            programList.add(5,(jCBSet6.getSelectedItem()).toString());
            programList.add(6,(jCBSet7.getSelectedItem()).toString());
            programList.add(7,(jCBSet8.getSelectedItem()).toString());
            new Maze(getNameMap());
        } catch (IOException ex) {
            Logger.getLogger(BotCount.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnNextActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(BotCount.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(BotCount.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(BotCount.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(BotCount.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new BotCount().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnExit;
    private javax.swing.JButton btnHide;
    private javax.swing.JButton btnNext;
    private javax.swing.JComboBox<String> jCBSet1;
    private javax.swing.JComboBox<String> jCBSet2;
    private javax.swing.JComboBox<String> jCBSet3;
    private javax.swing.JComboBox<String> jCBSet4;
    private javax.swing.JComboBox<String> jCBSet5;
    private javax.swing.JComboBox<String> jCBSet6;
    private javax.swing.JComboBox<String> jCBSet7;
    private javax.swing.JComboBox<String> jCBSet8;
    private javax.swing.JLabel lblBot1;
    private javax.swing.JLabel lblBot2;
    private javax.swing.JLabel lblBot3;
    private javax.swing.JLabel lblBot4;
    private javax.swing.JLabel lblBot5;
    private javax.swing.JLabel lblBot6;
    private javax.swing.JLabel lblBot7;
    private javax.swing.JLabel lblBot8;
    private javax.swing.JLabel lblColor1;
    private javax.swing.JLabel lblColor2;
    private javax.swing.JLabel lblColor3;
    private javax.swing.JLabel lblColor4;
    private javax.swing.JLabel lblColor5;
    private javax.swing.JLabel lblColor6;
    private javax.swing.JLabel lblColor7;
    private javax.swing.JLabel lblColor8;
    private javax.swing.JLabel lblSet1;
    private javax.swing.JLabel lblSet10;
    private javax.swing.JLabel lblSet11;
    private javax.swing.JLabel lblSet12;
    private javax.swing.JLabel lblSet13;
    private javax.swing.JLabel lblSet14;
    private javax.swing.JLabel lblSet15;
    private javax.swing.JLabel lblSet16;
    private javax.swing.JLabel lblSet2;
    private javax.swing.JLabel lblSet3;
    private javax.swing.JLabel lblSet4;
    private javax.swing.JLabel lblSet5;
    private javax.swing.JLabel lblSet6;
    private javax.swing.JLabel lblSet7;
    private javax.swing.JLabel lblSet8;
    private javax.swing.JLabel lblSet9;
    private javax.swing.JPanel pnlBody;
    private javax.swing.JPanel pnlBot1;
    private javax.swing.JPanel pnlBot2;
    private javax.swing.JPanel pnlBot3;
    private javax.swing.JPanel pnlBot4;
    private javax.swing.JPanel pnlBot5;
    private javax.swing.JPanel pnlBot6;
    private javax.swing.JPanel pnlBot7;
    private javax.swing.JPanel pnlBot8;
    private javax.swing.JPanel pnlColor1;
    private javax.swing.JPanel pnlColor2;
    private javax.swing.JPanel pnlColor3;
    private javax.swing.JPanel pnlColor4;
    private javax.swing.JPanel pnlColor5;
    private javax.swing.JPanel pnlColor6;
    private javax.swing.JPanel pnlColor7;
    private javax.swing.JPanel pnlColor8;
    private javax.swing.JPanel pnlHead;
    // End of variables declaration//GEN-END:variables
}
