/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import java.awt.Color;
import java.io.File;
import java.io.IOException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author 7heXiMiK
 */
public class MainMenu extends javax.swing.JFrame {

    /**
     * @return the PIB
     */
    public static String getPIB() {
        return PIB;
    }

    /**
     * @param aPIB the PIB to set
     */
    public static void setPIB(String aPIB) {
        PIB = aPIB;
    }
    private static String PIB = "";
    private ImageIcon icon = null;
    private String[] BotCount = {"1",
        "2",
        "3",
        "4",
        "5",
        "6",
        "7",
        "8",};
    DB d = new DB();
    public static String choice = "";
    MazeT t = new MazeT();
    public static ArrayList<String> mapList = new ArrayList<String>();
    static boolean levelsExistAlready = false;

    /**
     * Creates new form Main
     */
    public MainMenu() {
        initComponents();
        File IconForm = new File("Photo/labyrinth.png");
        try {
            this.setIconImage(ImageIO.read(IconForm));
        } catch (IOException ex) {
            Logger.getLogger(MainMenu.class.getName()).log(Level.SEVERE, null, ex);
        }
        this.setLocationRelativeTo(null);
        MoveMouseListener mml = new MoveMouseListener(pnlHead, this);
        pnlHead.addMouseListener(mml);
        pnlHead.addMouseMotionListener(mml);
        lblUser.setText("Користувач: " + getPIB());
    }

    String getLevelChoice() {
        mapList.clear();
        d.Connect();
        d.GetInfoBox("name_maze", "maze_info");
        for (int i = 0; i < d.list.size(); i++) {
            mapList.add(d.array[i]);
        }
        if (mapList.size() != 0) {
            String maps[] = new String[mapList.size() + 20];
            System.out.println(mapList.size());
            mapList.toArray(maps);
            choice = (String) JOptionPane.showInputDialog(null, "Оберіть карту", "Доступні карти", JOptionPane.QUESTION_MESSAGE, null, maps, maps[0]);
            System.out.println(choice);
            if (choice != null) {
                return choice;
            } else if (choice == null) {
                return null;
            }
        }
        return null;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        JPnlPlay5 = new javax.swing.JPanel();
        jLablePlay5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        JPnlPlay4 = new javax.swing.JPanel();
        jLablePlay8 = new javax.swing.JLabel();
        lblPlay2 = new javax.swing.JLabel();
        pnlBody = new javax.swing.JPanel();
        pnlHead = new javax.swing.JPanel();
        lblPhoto = new javax.swing.JLabel();
        lblText1 = new javax.swing.JLabel();
        JPnlPlay = new javax.swing.JPanel();
        jLablePlay = new javax.swing.JLabel();
        lblPlay = new javax.swing.JLabel();
        pnlDel = new javax.swing.JPanel();
        jLablePlay9 = new javax.swing.JLabel();
        lblPlay3 = new javax.swing.JLabel();
        JPnlEdit = new javax.swing.JPanel();
        jLablePlay1 = new javax.swing.JLabel();
        lblEdit = new javax.swing.JLabel();
        JPnlCreate = new javax.swing.JPanel();
        lblGen = new javax.swing.JLabel();
        jLablePlay4 = new javax.swing.JLabel();
        JPnlExit = new javax.swing.JPanel();
        jLablePlay6 = new javax.swing.JLabel();
        lblExit = new javax.swing.JLabel();
        pnlAll = new javax.swing.JPanel();
        jLablePlay7 = new javax.swing.JLabel();
        lblPlay1 = new javax.swing.JLabel();
        pnlSearch = new javax.swing.JPanel();
        jLablePlay10 = new javax.swing.JLabel();
        lblPlay4 = new javax.swing.JLabel();
        pnlAlg = new javax.swing.JPanel();
        lblTXTAlg = new javax.swing.JLabel();
        lblAlg = new javax.swing.JLabel();
        lblUser = new javax.swing.JLabel();

        JPnlPlay5.setBackground(new java.awt.Color(0, 51, 204));

        jLablePlay5.setFont(new java.awt.Font("Times New Roman", 3, 18)); // NOI18N
        jLablePlay5.setForeground(new java.awt.Color(255, 255, 255));
        jLablePlay5.setText("Грати");

        jLabel6.setBackground(new java.awt.Color(0, 51, 204));
        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Photo/play.png"))); // NOI18N

        javax.swing.GroupLayout JPnlPlay5Layout = new javax.swing.GroupLayout(JPnlPlay5);
        JPnlPlay5.setLayout(JPnlPlay5Layout);
        JPnlPlay5Layout.setHorizontalGroup(
            JPnlPlay5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JPnlPlay5Layout.createSequentialGroup()
                .addGroup(JPnlPlay5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, JPnlPlay5Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel6))
                    .addGroup(JPnlPlay5Layout.createSequentialGroup()
                        .addGap(39, 39, 39)
                        .addComponent(jLablePlay5)))
                .addContainerGap())
        );
        JPnlPlay5Layout.setVerticalGroup(
            JPnlPlay5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, JPnlPlay5Layout.createSequentialGroup()
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLablePlay5))
        );

        JPnlPlay4.setBackground(new java.awt.Color(0, 51, 204));
        JPnlPlay4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                JPnlPlay4MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                JPnlPlay4MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                JPnlPlay4MouseExited(evt);
            }
        });

        jLablePlay8.setFont(new java.awt.Font("Times New Roman", 3, 18)); // NOI18N
        jLablePlay8.setForeground(new java.awt.Color(255, 255, 255));
        jLablePlay8.setText("Грати");

        lblPlay2.setBackground(new java.awt.Color(0, 51, 204));
        lblPlay2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Photo/play.png"))); // NOI18N

        javax.swing.GroupLayout JPnlPlay4Layout = new javax.swing.GroupLayout(JPnlPlay4);
        JPnlPlay4.setLayout(JPnlPlay4Layout);
        JPnlPlay4Layout.setHorizontalGroup(
            JPnlPlay4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JPnlPlay4Layout.createSequentialGroup()
                .addGroup(JPnlPlay4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(JPnlPlay4Layout.createSequentialGroup()
                        .addGap(43, 43, 43)
                        .addComponent(jLablePlay8))
                    .addGroup(JPnlPlay4Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lblPlay2)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        JPnlPlay4Layout.setVerticalGroup(
            JPnlPlay4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, JPnlPlay4Layout.createSequentialGroup()
                .addComponent(lblPlay2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLablePlay8)
                .addContainerGap())
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        pnlBody.setBackground(new java.awt.Color(0, 0, 102));

        pnlHead.setBackground(new java.awt.Color(0, 51, 204));

        lblPhoto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Photo/maze.png"))); // NOI18N

        lblText1.setFont(new java.awt.Font("Times New Roman", 1, 48)); // NOI18N
        lblText1.setForeground(new java.awt.Color(255, 255, 255));
        lblText1.setText("Середовище для змагання ботів");

        javax.swing.GroupLayout pnlHeadLayout = new javax.swing.GroupLayout(pnlHead);
        pnlHead.setLayout(pnlHeadLayout);
        pnlHeadLayout.setHorizontalGroup(
            pnlHeadLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlHeadLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(lblPhoto)
                .addGap(30, 30, 30)
                .addComponent(lblText1)
                .addContainerGap(45, Short.MAX_VALUE))
        );
        pnlHeadLayout.setVerticalGroup(
            pnlHeadLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlHeadLayout.createSequentialGroup()
                .addGroup(pnlHeadLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlHeadLayout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addComponent(lblPhoto, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnlHeadLayout.createSequentialGroup()
                        .addGap(50, 50, 50)
                        .addComponent(lblText1)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        JPnlPlay.setBackground(new java.awt.Color(0, 51, 204));
        JPnlPlay.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                JPnlPlayMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                JPnlPlayMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                JPnlPlayMouseExited(evt);
            }
        });

        jLablePlay.setFont(new java.awt.Font("Times New Roman", 3, 18)); // NOI18N
        jLablePlay.setForeground(new java.awt.Color(255, 255, 255));
        jLablePlay.setText("Грати");

        lblPlay.setBackground(new java.awt.Color(0, 51, 204));
        lblPlay.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Photo/play.png"))); // NOI18N

        javax.swing.GroupLayout JPnlPlayLayout = new javax.swing.GroupLayout(JPnlPlay);
        JPnlPlay.setLayout(JPnlPlayLayout);
        JPnlPlayLayout.setHorizontalGroup(
            JPnlPlayLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, JPnlPlayLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblPlay)
                .addContainerGap())
            .addGroup(JPnlPlayLayout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addComponent(jLablePlay)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        JPnlPlayLayout.setVerticalGroup(
            JPnlPlayLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, JPnlPlayLayout.createSequentialGroup()
                .addComponent(lblPlay)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLablePlay)
                .addContainerGap())
        );

        pnlDel.setBackground(new java.awt.Color(0, 51, 204));
        pnlDel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pnlDelMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                pnlDelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                pnlDelMouseExited(evt);
            }
        });

        jLablePlay9.setFont(new java.awt.Font("Times New Roman", 3, 18)); // NOI18N
        jLablePlay9.setForeground(new java.awt.Color(255, 255, 255));
        jLablePlay9.setText("Видалити");

        lblPlay3.setBackground(new java.awt.Color(0, 51, 204));
        lblPlay3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Photo/interface.png"))); // NOI18N

        javax.swing.GroupLayout pnlDelLayout = new javax.swing.GroupLayout(pnlDel);
        pnlDel.setLayout(pnlDelLayout);
        pnlDelLayout.setHorizontalGroup(
            pnlDelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlDelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(pnlDelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlDelLayout.createSequentialGroup()
                        .addComponent(lblPlay3)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlDelLayout.createSequentialGroup()
                        .addComponent(jLablePlay9)
                        .addGap(24, 24, 24))))
        );
        pnlDelLayout.setVerticalGroup(
            pnlDelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlDelLayout.createSequentialGroup()
                .addComponent(lblPlay3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLablePlay9)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        JPnlEdit.setBackground(new java.awt.Color(0, 51, 204));
        JPnlEdit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                JPnlEditMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                JPnlEditMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                JPnlEditMouseExited(evt);
            }
        });

        jLablePlay1.setFont(new java.awt.Font("Times New Roman", 3, 18)); // NOI18N
        jLablePlay1.setForeground(new java.awt.Color(255, 255, 255));
        jLablePlay1.setText("Редагувати");

        lblEdit.setBackground(new java.awt.Color(0, 51, 204));
        lblEdit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Photo/pencil_1.png"))); // NOI18N

        javax.swing.GroupLayout JPnlEditLayout = new javax.swing.GroupLayout(JPnlEdit);
        JPnlEdit.setLayout(JPnlEditLayout);
        JPnlEditLayout.setHorizontalGroup(
            JPnlEditLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JPnlEditLayout.createSequentialGroup()
                .addGap(5, 5, 5)
                .addComponent(lblEdit)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, JPnlEditLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLablePlay1)
                .addGap(20, 20, 20))
        );
        JPnlEditLayout.setVerticalGroup(
            JPnlEditLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, JPnlEditLayout.createSequentialGroup()
                .addComponent(lblEdit)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLablePlay1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        JPnlCreate.setBackground(new java.awt.Color(0, 51, 204));
        JPnlCreate.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                JPnlCreateMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                JPnlCreateMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                JPnlCreateMouseExited(evt);
            }
        });

        lblGen.setBackground(new java.awt.Color(0, 51, 204));
        lblGen.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Photo/hydro-power.png"))); // NOI18N

        jLablePlay4.setFont(new java.awt.Font("Times New Roman", 3, 18)); // NOI18N
        jLablePlay4.setForeground(new java.awt.Color(255, 255, 255));
        jLablePlay4.setText("Створити");

        javax.swing.GroupLayout JPnlCreateLayout = new javax.swing.GroupLayout(JPnlCreate);
        JPnlCreate.setLayout(JPnlCreateLayout);
        JPnlCreateLayout.setHorizontalGroup(
            JPnlCreateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JPnlCreateLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(JPnlCreateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, JPnlCreateLayout.createSequentialGroup()
                        .addComponent(jLablePlay4)
                        .addGap(23, 23, 23))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, JPnlCreateLayout.createSequentialGroup()
                        .addComponent(lblGen)
                        .addContainerGap())))
        );
        JPnlCreateLayout.setVerticalGroup(
            JPnlCreateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JPnlCreateLayout.createSequentialGroup()
                .addComponent(lblGen)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLablePlay4)
                .addContainerGap())
        );

        JPnlExit.setBackground(new java.awt.Color(0, 51, 204));
        JPnlExit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                JPnlExitMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                JPnlExitMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                JPnlExitMouseExited(evt);
            }
        });

        jLablePlay6.setFont(new java.awt.Font("Times New Roman", 3, 18)); // NOI18N
        jLablePlay6.setForeground(new java.awt.Color(255, 255, 255));
        jLablePlay6.setText("Вихід");

        lblExit.setBackground(new java.awt.Color(0, 51, 204));
        lblExit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Photo/emergency-exit.png"))); // NOI18N

        javax.swing.GroupLayout JPnlExitLayout = new javax.swing.GroupLayout(JPnlExit);
        JPnlExit.setLayout(JPnlExitLayout);
        JPnlExitLayout.setHorizontalGroup(
            JPnlExitLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JPnlExitLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(JPnlExitLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(JPnlExitLayout.createSequentialGroup()
                        .addComponent(lblExit)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, JPnlExitLayout.createSequentialGroup()
                        .addComponent(jLablePlay6)
                        .addGap(45, 45, 45))))
        );
        JPnlExitLayout.setVerticalGroup(
            JPnlExitLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, JPnlExitLayout.createSequentialGroup()
                .addComponent(lblExit)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLablePlay6)
                .addContainerGap())
        );

        pnlAll.setBackground(new java.awt.Color(0, 51, 204));
        pnlAll.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pnlAllMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                pnlAllMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                pnlAllMouseExited(evt);
            }
        });

        jLablePlay7.setFont(new java.awt.Font("Times New Roman", 3, 18)); // NOI18N
        jLablePlay7.setForeground(new java.awt.Color(255, 255, 255));
        jLablePlay7.setText("Доступні");

        lblPlay1.setBackground(new java.awt.Color(0, 51, 204));
        lblPlay1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Photo/education (1).png"))); // NOI18N

        javax.swing.GroupLayout pnlAllLayout = new javax.swing.GroupLayout(pnlAll);
        pnlAll.setLayout(pnlAllLayout);
        pnlAllLayout.setHorizontalGroup(
            pnlAllLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlAllLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(pnlAllLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlAllLayout.createSequentialGroup()
                        .addComponent(lblPlay1)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlAllLayout.createSequentialGroup()
                        .addComponent(jLablePlay7)
                        .addGap(28, 28, 28))))
        );
        pnlAllLayout.setVerticalGroup(
            pnlAllLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlAllLayout.createSequentialGroup()
                .addComponent(lblPlay1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLablePlay7)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pnlSearch.setBackground(new java.awt.Color(0, 51, 204));
        pnlSearch.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pnlSearchMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                pnlSearchMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                pnlSearchMouseExited(evt);
            }
        });

        jLablePlay10.setFont(new java.awt.Font("Times New Roman", 3, 18)); // NOI18N
        jLablePlay10.setForeground(new java.awt.Color(255, 255, 255));
        jLablePlay10.setText("Пошук");

        lblPlay4.setBackground(new java.awt.Color(0, 51, 204));
        lblPlay4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Photo/search (1).png"))); // NOI18N

        javax.swing.GroupLayout pnlSearchLayout = new javax.swing.GroupLayout(pnlSearch);
        pnlSearch.setLayout(pnlSearchLayout);
        pnlSearchLayout.setHorizontalGroup(
            pnlSearchLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlSearchLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblPlay4)
                .addContainerGap())
            .addGroup(pnlSearchLayout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addComponent(jLablePlay10)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnlSearchLayout.setVerticalGroup(
            pnlSearchLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlSearchLayout.createSequentialGroup()
                .addComponent(lblPlay4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLablePlay10)
                .addContainerGap())
        );

        pnlAlg.setBackground(new java.awt.Color(0, 51, 204));
        pnlAlg.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pnlAlgMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                pnlAlgMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                pnlAlgMouseExited(evt);
            }
        });

        lblTXTAlg.setFont(new java.awt.Font("Times New Roman", 3, 18)); // NOI18N
        lblTXTAlg.setForeground(new java.awt.Color(255, 255, 255));
        lblTXTAlg.setText("Алгоритм");

        lblAlg.setBackground(new java.awt.Color(0, 51, 204));
        lblAlg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Photo/algoritmo (2).png"))); // NOI18N

        javax.swing.GroupLayout pnlAlgLayout = new javax.swing.GroupLayout(pnlAlg);
        pnlAlg.setLayout(pnlAlgLayout);
        pnlAlgLayout.setHorizontalGroup(
            pnlAlgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlAlgLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblAlg)
                .addContainerGap())
            .addGroup(pnlAlgLayout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(lblTXTAlg)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnlAlgLayout.setVerticalGroup(
            pnlAlgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlAlgLayout.createSequentialGroup()
                .addComponent(lblAlg)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblTXTAlg)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        lblUser.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        lblUser.setForeground(new java.awt.Color(255, 255, 255));
        lblUser.setText("Користувач:");

        javax.swing.GroupLayout pnlBodyLayout = new javax.swing.GroupLayout(pnlBody);
        pnlBody.setLayout(pnlBodyLayout);
        pnlBodyLayout.setHorizontalGroup(
            pnlBodyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlHead, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(pnlBodyLayout.createSequentialGroup()
                .addGap(71, 71, 71)
                .addGroup(pnlBodyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblUser)
                    .addGroup(pnlBodyLayout.createSequentialGroup()
                        .addGroup(pnlBodyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(JPnlPlay, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(pnlSearch, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(76, 76, 76)
                        .addGroup(pnlBodyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(pnlDel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(pnlAlg, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(78, 78, 78)
                        .addGroup(pnlBodyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(pnlBodyLayout.createSequentialGroup()
                                .addComponent(pnlAll, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(JPnlExit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(pnlBodyLayout.createSequentialGroup()
                                .addComponent(JPnlEdit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(78, 78, 78)
                                .addComponent(JPnlCreate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnlBodyLayout.setVerticalGroup(
            pnlBodyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlBodyLayout.createSequentialGroup()
                .addComponent(pnlHead, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(pnlBodyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(pnlAlg, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(JPnlEdit, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(JPnlPlay, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(JPnlCreate, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(29, 29, 29)
                .addGroup(pnlBodyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pnlAll, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pnlDel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pnlSearch, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(JPnlExit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(3, 3, 3)
                .addComponent(lblUser, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlBody, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlBody, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void JPnlPlayMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JPnlPlayMouseClicked
        //Старт
        // try {
        // show();
        BotCount botC = null;
        String s = getLevelChoice();
        if (s != null) {
            // JOptionPane.showMessageDialog(rootPane, "Успішно", "Пошук", HEIGHT);
            Object[] options = {"Пройти лабіринт самостійно", "Застосувати алгоритм для лабіринту"};
            int n = JOptionPane.showOptionDialog(rootPane,
                    "Виберіть метод роботи з лабіринтом: " + s,
                    "Вибір дії",
                    JOptionPane.DEFAULT_OPTION,
                    JOptionPane.QUESTION_MESSAGE,
                    null,
                    options,
                    options[0]);
            System.out.println(n);
            if (n == -1) {
            } else if (n == 1) {
                String result = (String) JOptionPane.showInputDialog(
                        rootPane,
                        "Виберіть кількість ботів :",
                        "Вибір кількості ботів",
                        JOptionPane.QUESTION_MESSAGE,
                        icon, BotCount, BotCount[0]);
                if (result == null) {
                } else {
                    botC.setBotCoutn(Integer.parseInt(result));
                    Maze.setHowDo(n);
                    botC.setNameMap(s);
                    botC = new BotCount();
                    this.setVisible(false);
                    botC.setVisible(true);
                }
            } else if (n == 0) {
                try {
                    // this.setVisible(false);
                    this.dispose();
                    Maze.setHowDo(n);
                    new Maze(s);
                } catch (IOException ex) {
                    Logger.getLogger(MainMenu.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        } else {
        }
    }//GEN-LAST:event_JPnlPlayMouseClicked

    private void JPnlEditMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JPnlEditMouseClicked
        //Редагування
        String s = getLevelChoice();
        if (s != null) {
            try {
                new MazeMapMaker(s);
                this.dispose();
            } catch (IOException ex) {
                Logger.getLogger(MainMenu.class.getName()).log(Level.SEVERE, null, ex);
            }
        } else {
        }


    }//GEN-LAST:event_JPnlEditMouseClicked

    private void JPnlCreateMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JPnlCreateMouseClicked
        //Створення
        try {
            DB a = new DB();
            a.Connect();
            t.Generate();
            a.Connect();
        } catch (IOException ex) {
            Logger.getLogger(MainMenu.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_JPnlCreateMouseClicked

    private void JPnlExitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JPnlExitMouseClicked
        System.exit(0);
    }//GEN-LAST:event_JPnlExitMouseClicked

    private void JPnlPlayMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JPnlPlayMouseEntered
        JPnlPlay.setBackground(new Color(102, 0, 204));
    }//GEN-LAST:event_JPnlPlayMouseEntered

    private void JPnlPlayMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JPnlPlayMouseExited
        JPnlPlay.setBackground(new Color(0, 51, 204));
    }//GEN-LAST:event_JPnlPlayMouseExited

    private void JPnlEditMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JPnlEditMouseEntered
        JPnlEdit.setBackground(new Color(102, 0, 204));
    }//GEN-LAST:event_JPnlEditMouseEntered

    private void JPnlEditMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JPnlEditMouseExited
        JPnlEdit.setBackground(new Color(0, 51, 204));
    }//GEN-LAST:event_JPnlEditMouseExited

    private void JPnlCreateMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JPnlCreateMouseEntered
        JPnlCreate.setBackground(new Color(102, 0, 204));
    }//GEN-LAST:event_JPnlCreateMouseEntered

    private void JPnlCreateMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JPnlCreateMouseExited
        JPnlCreate.setBackground(new Color(0, 51, 204));
    }//GEN-LAST:event_JPnlCreateMouseExited

    private void JPnlExitMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JPnlExitMouseEntered
        JPnlExit.setBackground(new Color(102, 0, 204));
    }//GEN-LAST:event_JPnlExitMouseEntered

    private void JPnlExitMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JPnlExitMouseExited
        JPnlExit.setBackground(new Color(0, 51, 204));
    }//GEN-LAST:event_JPnlExitMouseExited

    private void pnlAllMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlAllMouseClicked
        // TODO add your handling code here:
        d.Connect();
        mapList.clear();
        d.GetInfoBox("name_maze", "maze_info");
        for (int i = 0; i < d.list.size(); i++) {
            mapList.add(d.array[i]);
        }
        if (mapList.size() != 0) {
            String maps[] = new String[mapList.size() + 20];
            System.out.println(mapList.size());
            mapList.toArray(maps);
            choice = (String) JOptionPane.showInputDialog(null, "", "Доступні карти", JOptionPane.QUESTION_MESSAGE, null, maps, maps[0]);
        }
    }//GEN-LAST:event_pnlAllMouseClicked

    private void pnlAllMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlAllMouseEntered
        pnlAll.setBackground(new Color(102, 0, 204));
    }//GEN-LAST:event_pnlAllMouseEntered

    private void pnlAllMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlAllMouseExited
        pnlAll.setBackground(new Color(0, 51, 204));
    }//GEN-LAST:event_pnlAllMouseExited

    private void JPnlPlay4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JPnlPlay4MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_JPnlPlay4MouseClicked

    private void JPnlPlay4MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JPnlPlay4MouseEntered
        JPnlExit.setBackground(new Color(102, 0, 204));
    }//GEN-LAST:event_JPnlPlay4MouseEntered

    private void JPnlPlay4MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JPnlPlay4MouseExited
        JPnlExit.setBackground(new Color(0, 51, 204));
    }//GEN-LAST:event_JPnlPlay4MouseExited

    private void pnlDelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlDelMouseClicked
        d.Connect();
        String name = null;
        Object[] options = {"Вибрати з усіх", "Ввести назву"};
        int n = JOptionPane.showOptionDialog(rootPane,
                "Виберіть зручний для вас спосіб: ",
                "Вибір лабіринту",
                JOptionPane.DEFAULT_OPTION,
                JOptionPane.QUESTION_MESSAGE,
                null,
                options,
                options[1]);
        if (n == 0) {
            name = getLevelChoice();
        } else if (n == 1) {
            name = JOptionPane.showInputDialog(rootPane, "Введіть назву лабіринту");
        }
        try {
            d.setNameMaze(null);
            d.GetMaze(name);
            if (d.getNameMaze() != null && name.length() > 0) {
                String[] btn = {"Так", "Ні"};
                int a = JOptionPane.showOptionDialog(null, "Ви дійсно хочете видалити лабіринт: " + name, "Підтвердження",
                        JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE, null, btn, "OK");
                if (a == JOptionPane.YES_OPTION) {
                    d.del(name);
                    d.Connect();
                } else if (a == JOptionPane.CANCEL_OPTION) {
                }
            } else if (name.length() == 0) {
                JOptionPane.showMessageDialog(rootPane, "Помилка", "Видалення", HEIGHT);
            } else if (d.getNameMaze() == null) {
                JOptionPane.showMessageDialog(rootPane, "Лабіринту не існує", "Видалення", HEIGHT);
            } else {
            }
        } catch (Exception ex) {
        }
    }//GEN-LAST:event_pnlDelMouseClicked

    private void pnlDelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlDelMouseEntered
        pnlDel.setBackground(new Color(102, 0, 204));
    }//GEN-LAST:event_pnlDelMouseEntered

    private void pnlDelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlDelMouseExited
        pnlDel.setBackground(new Color(0, 51, 204));
    }//GEN-LAST:event_pnlDelMouseExited

    private void pnlSearchMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlSearchMouseClicked
        // TODO add your handling code here:
        d.Connect();
        String name = JOptionPane.showInputDialog(rootPane, "Введіть назву лабіринту","Пошук",JOptionPane.QUESTION_MESSAGE);
        d.setNameMaze(null);
        try {
            d.GetMaze(name);
            if (d.getNameMaze() != null && name.length() > 0) {
                int k = 2;
                JOptionPane.showMessageDialog(rootPane, "Успішно", "Пошук", HEIGHT);
                Object[] options = {"Грати", "Редагувати",
                    "Видалити",
                    "Назад"};
                do {
                    int n = JOptionPane.showOptionDialog(rootPane,
                            "Виберіть дію для лабіринту: " + name,
                            "Вибір дії",
                            JOptionPane.DEFAULT_OPTION,
                            JOptionPane.QUESTION_MESSAGE,
                            null,
                            options,
                            options[2]);
                    if (n == 0) {
                        if (name != null) {
                            BotCount botC = null;
                            Object[] options1 = {"Пройти лабіринт самостійно", "Застосувати алгоритм для лабіринту"};
                            int v = JOptionPane.showOptionDialog(rootPane,
                                    "Виберіть роботи з лабіринтом: " + name,
                                    "Вибір дії",
                                    JOptionPane.DEFAULT_OPTION,
                                    JOptionPane.QUESTION_MESSAGE,
                                    null,
                                    options1,
                                    options1[0]);
                            System.out.println(n);
                            if (v == -1) {
                            } else if (v == 1) {
                                String result = (String) JOptionPane.showInputDialog(
                                        rootPane,
                                        "Виберіть кількість ботів :",
                                        "Вибір кількості ботів",
                                        JOptionPane.QUESTION_MESSAGE,
                                        icon, BotCount, BotCount[0]);
                                if (result == null) {
                                } else {
                                    botC.setBotCoutn(Integer.parseInt(result));
                                    Maze.setHowDo(v);
                                    botC.setNameMap(name);
                                    botC = new BotCount();
                                    this.setVisible(false);
                                    botC.setVisible(true);
                                }
                            } else if (v == 0) {
                                try {
                                    // this.setVisible(false);
                                    this.dispose();
                                    Maze.setHowDo(v);
                                    new Maze(name);
                                } catch (IOException ex) {
                                    Logger.getLogger(MainMenu.class.getName()).log(Level.SEVERE, null, ex);
                                }
                            }
                        } else {
                        }
                        k = 0;
                    } else if (n == 1) {
                        //Редагувати
                        try {
                            new MazeMapMaker(name);
                            this.dispose();
                            k = 0;
                        } catch (IOException ex) {
                            Logger.getLogger(MainMenu.class.getName()).log(Level.SEVERE, null, ex);
                        }
                    } else if (n == 2) {
                        //Видалити
                        String[] btn = {"Так", "Ні"};
                        int a = JOptionPane.showOptionDialog(null, "Ви дійсно хочете видалити лабіринт: " + name, "Підтвердження",
                                JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE, null, btn, "OK");
                        if (a == JOptionPane.YES_OPTION) {
                            d.del(name);
                            d.Connect();
                            k = 0;
                        } else {
                        }
                    } else if (n == 3) {
                        //Назад
                        k = 0;
                    } else {
                        k = 0;
                    }
                } while (k > 0);
            } else if (name.length() == 0) {
                JOptionPane.showMessageDialog(rootPane, "Помилка", "Пошук", HEIGHT);
            } else if (d.getNameMaze() == null) {
                JOptionPane.showMessageDialog(rootPane, "Лабіринту не існує", "Пошук", HEIGHT);
            } else {
            }
        } catch (Exception ex) {
        }
    }//GEN-LAST:event_pnlSearchMouseClicked

    private void pnlSearchMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlSearchMouseEntered
        pnlSearch.setBackground(new Color(102, 0, 204));
    }//GEN-LAST:event_pnlSearchMouseEntered

    private void pnlSearchMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlSearchMouseExited
        pnlSearch.setBackground(new Color(0, 51, 204));
    }//GEN-LAST:event_pnlSearchMouseExited

    private void pnlAlgMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlAlgMouseClicked
        this.dispose();
        AlgorithmMenu a = new AlgorithmMenu();
        a.setVisible(true);
    }//GEN-LAST:event_pnlAlgMouseClicked

    private void pnlAlgMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlAlgMouseEntered
        pnlAlg.setBackground(new Color(102, 0, 204));
    }//GEN-LAST:event_pnlAlgMouseEntered

    private void pnlAlgMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlAlgMouseExited
        pnlAlg.setBackground(new Color(0, 51, 204));
    }//GEN-LAST:event_pnlAlgMouseExited

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;

                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainMenu.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainMenu.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainMenu.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainMenu.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainMenu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel JPnlCreate;
    private javax.swing.JPanel JPnlEdit;
    private javax.swing.JPanel JPnlExit;
    private javax.swing.JPanel JPnlPlay;
    private javax.swing.JPanel JPnlPlay4;
    private javax.swing.JPanel JPnlPlay5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLablePlay;
    private javax.swing.JLabel jLablePlay1;
    private javax.swing.JLabel jLablePlay10;
    private javax.swing.JLabel jLablePlay4;
    private javax.swing.JLabel jLablePlay5;
    private javax.swing.JLabel jLablePlay6;
    private javax.swing.JLabel jLablePlay7;
    private javax.swing.JLabel jLablePlay8;
    private javax.swing.JLabel jLablePlay9;
    private javax.swing.JLabel lblAlg;
    private javax.swing.JLabel lblEdit;
    private javax.swing.JLabel lblExit;
    private javax.swing.JLabel lblGen;
    private javax.swing.JLabel lblPhoto;
    private javax.swing.JLabel lblPlay;
    private javax.swing.JLabel lblPlay1;
    private javax.swing.JLabel lblPlay2;
    private javax.swing.JLabel lblPlay3;
    private javax.swing.JLabel lblPlay4;
    private javax.swing.JLabel lblTXTAlg;
    private javax.swing.JLabel lblText1;
    private javax.swing.JLabel lblUser;
    private javax.swing.JPanel pnlAlg;
    private javax.swing.JPanel pnlAll;
    private javax.swing.JPanel pnlBody;
    private javax.swing.JPanel pnlDel;
    private javax.swing.JPanel pnlHead;
    private javax.swing.JPanel pnlSearch;
    // End of variables declaration//GEN-END:variables
}
